const fs = require('fs');
const path = require('path');

const dictionaries = {
  "en": {
    "nav": {
      "dashboard": "Dashboard",
      "today": "TODAY",
      "rhythm": "RHYTHM",
      "protocols": "Protocols",
      "cycleTracking": "Cycle Tracking",
      "community": "Community",
      "log": "LOG",
      "me": "ME",
      "welcomeBack": "Welcome back",
      "rhythmSteady": "Your rhythm is steady",
      "logActivity": "Log Activity",
      "support": "Support",
      "logout": "Logout",
      "language": "Language"
    },
    "home": {
      "goodMorning": "Good morning",
      "welcomeBack": "Welcome back",
      "energyDay": "Today is a high-energy day in your cycle. Embrace the movement.",
      "daysInRow": "DAYS IN A ROW",
      "todaysProtocol": "Today's Protocol",
      "weeklyRhythm": "Weekly Rhythm",
      "synced": "SYNCED",
      "energyLevel": "Energy Level",
      "optimal": "Optimal",
      "status": "STATUS",
      "rhythmRecovery": "Rhythm Recovery",
      "lutealPhase": "Luteal Phase",
      "percentOptimal": "78% Optimal",
      "quote": "\"Take gentle movements today; your body is preparing for rest.\"",
      "hormoneTracking": "Hormone Tracking",
      "loggedAgo": "Logged 2h ago",
      "rhythmCalendar": "Rhythm Calendar",
      "nextState": "Next: Flow State",
      "activityRecord": "Activity Record",
      "seeTrends": "See Trends",
      "premiumInsight": "Premium Insight",
      "monthlyTrend": "Monthly Hormonal Trend Report",
      "premiumText": "We've analyzed your past 30 days of activity and biometric data. Your follicular phase is showing significant improvement in resting heart rate variability.",
      "viewReport": "VIEW FULL REPORT",
      "needRecord": "Record Needed 🌿",
      "recordDesc": "Take 1 minute today to listen to the small changes in your body.",
      "checkinNow": "Start Today's Check-in",
      "howIsCycle": "Are you riding your cycle well?",
      "startCheckin": "Start Check-in",
      "currentActionRule": "Action guidelines tailored to your body's voice",
      "tasks": {
        "t1_title": "Morning Walk",
        "t1_sub": "20 minutes outdoors for cortisol regulation",
        "t2_title": "Hydration Target",
        "t2_sub": "2.5L with electrolyte support",
        "t3_title": "Sleep Quality Log",
        "t3_sub": "Track REM and Deep Sleep cycles"
      }
    },
    "onboarding": {
      "findingRhythm": "Finding your rhythm",
      "tailorExperience": "We'll tailor your experience based on your current state and aspirations.",
      "primaryGoal": "What is your primary health goal?",
      "weightManagement": "Weight Management",
      "energyVitality": "Energy & Vitality",
      "mentalClarity": "Mental Clarity",
      "howCondition": "How is your general condition lately?",
      "shareAsMuch": "Share as much or as little as you like.",
      "placeholder": "Example: I've been feeling a bit sluggish in the mornings and finding it hard to focus after lunch...",
      "startJourney": "Start Journey",
      "skipForNow": "Skip for now",
      "configuring": "Configuring...",
      "craftedFor": "© 2024 For:M. Crafted for your sanctuary."
    }
  },
  "ko": {
    "nav": {
      "dashboard": "대시보드",
      "today": "오늘",
      "rhythm": "리듬",
      "protocols": "프로토콜",
      "cycleTracking": "주기 추적",
      "community": "커뮤니티",
      "log": "기록",
      "me": "내 정보",
      "welcomeBack": "환영합니다",
      "rhythmSteady": "리듬이 아주 안정적입니다",
      "logActivity": "활동 기록하기",
      "support": "고객지원",
      "logout": "로그아웃",
      "language": "언어 변경"
    },
    "home": {
      "goodMorning": "좋은 아침입니다",
      "welcomeBack": "환영합니다",
      "energyDay": "원기가 왕성한 날입니다. 활기찬 에너지를 마음껏 몸으로 표현하세요.",
      "daysInRow": "일 연속 기록",
      "todaysProtocol": "오늘의 프로토콜",
      "weeklyRhythm": "주간 리듬 현황",
      "synced": "동기화됨",
      "energyLevel": "에너지 레벨",
      "optimal": "최적",
      "status": "상태",
      "rhythmRecovery": "리듬 회복 중",
      "lutealPhase": "황체기",
      "percentOptimal": "78% 최적",
      "quote": "\"가벼운 움직임으로 시작하세요; 몸이 휴식을 준비하고 있습니다.\"",
      "hormoneTracking": "호르몬 추세",
      "loggedAgo": "2시간 전 기록됨",
      "rhythmCalendar": "리듬 캘린더",
      "nextState": "다음: 플로우 상태",
      "activityRecord": "활동 기록",
      "seeTrends": "트렌드 보기",
      "premiumInsight": "프리미엄 인사이트",
      "monthlyTrend": "월간 호르몬 트렌드 리포트",
      "premiumText": "지난 30일간의 활동과 생체 데이터를 분석했습니다. 여포기 상태에서 휴식기 심박 변이도에 유의미한 개선이 확인되었습니다.",
      "viewReport": "전체 리포트 보기",
      "needRecord": "리듬 기록 필요 🌿",
      "recordDesc": "하루 단 1분, 나의 몸이 보내는 작은 변화에 귀 기울여보세요.",
      "checkinNow": "오늘의 리듬 체크인하기",
      "howIsCycle": "당신의 주기는 안녕하신가요?",
      "startCheckin": "체크인 시작하기",
      "currentActionRule": "현재 몸의 소리에 맞는 행동 수칙",
      "tasks": {
        "t1_title": "가벼운 아침 산책",
        "t1_sub": "코르티솔 조절을 위한 20분 야외 걷기",
        "t2_title": "수분 섭취 목표",
        "t2_sub": "전해질을 포함한 2.5L 물 마시기",
        "t3_title": "수면 질 기록",
        "t3_sub": "렘수면 및 깊은 수면 사이클 분석"
      }
    },
    "onboarding": {
      "findingRhythm": "나만의 고유한 리듬 찾기",
      "tailorExperience": "현재의 상태와 목표를 분석하여 나에게 맞는 개인화된 코칭을 제공합니다.",
      "primaryGoal": "가장 개선하고 싶은 건강 목표가 무엇인가요?",
      "weightManagement": "체중 관리",
      "energyVitality": "에너지 & 활력",
      "mentalClarity": "정신적 맑음 (멘탈 케어)",
      "howCondition": "최근 전반적인 컨디션은 어떠신가요?",
      "shareAsMuch": "편하게, 원하는 만큼만 공유해 주세요.",
      "placeholder": "예: 아침에는 일어나는 게 유난히 힘들고 점심시간 이후에는 어김없이 집중이 잘 안돼요...",
      "startJourney": "여정 시작하기",
      "skipForNow": "건너뛰기",
      "configuring": "맞춤 설정 중...",
      "craftedFor": "© 2024 For:M. 오직 당신을 위해 설계된 안식처."
    }
  },
  "ja": {
    "nav": {
      "dashboard": "ダッシュボード",
      "today": "今日",
      "rhythm": "リズム",
      "protocols": "プロトコル",
      "cycleTracking": "周期記録",
      "community": "コミュニティ",
      "log": "記録",
      "me": "プロフィール",
      "welcomeBack": "お帰りなさい",
      "rhythmSteady": "リズムは安定しています",
      "logActivity": "アクティビティを記録",
      "support": "サポート",
      "logout": "ログアウト",
      "language": "言語"
    },
    "home": {
      "goodMorning": "おはようございます",
      "welcomeBack": "お帰りなさい",
      "energyDay": "本日はエネルギーレベルが高い日です。活発に動きましょう。",
      "daysInRow": "日連続記録",
      "todaysProtocol": "今日のプロトコル",
      "weeklyRhythm": "週間リズム",
      "synced": "同期率",
      "energyLevel": "エネルギーレベル",
      "optimal": "最適",
      "status": "ステータス",
      "rhythmRecovery": "リズム回復",
      "lutealPhase": "黄体期",
      "percentOptimal": "78% 最適",
      "quote": "「本日は軽い運動をお勧めします。体は休息の準備をしています。」",
      "hormoneTracking": "ホルモン記録",
      "loggedAgo": "2時間前に記録",
      "rhythmCalendar": "リズムカレンダー",
      "nextState": "次: フロー状態",
      "activityRecord": "アクティビティ記録",
      "seeTrends": "トレンドを見る",
      "premiumInsight": "プレミアムインサイト",
      "monthlyTrend": "月間ホルモントレンドレポート",
      "premiumText": "過去30日間の活動と生体データを分析しました。卵胞期において、安静時心拍変動の有意な改善が見られます。",
      "viewReport": "レポート全体を見る",
      "needRecord": "記録が必要です 🌿",
      "recordDesc": "1日1分、体の小さな変化に耳を傾けてみましょう。",
      "checkinNow": "今日のチェックインを開始",
      "howIsCycle": "生理周期はいかがですか？",
      "startCheckin": "チェックインを開始",
      "currentActionRule": "今の体の状態に合わせた行動のルール",
      "tasks": {
        "t1_title": "朝の散歩",
        "t1_sub": "コルチゾール調節のための屋外20分",
        "t2_title": "水分補給の目標",
        "t2_sub": "電解質を含む2.5L",
        "t3_title": "睡眠の質の記録",
        "t3_sub": "レム睡眠と深い睡眠のサイクルを記録"
      }
    },
    "onboarding": {
      "findingRhythm": "リズムを見つける",
      "tailorExperience": "現在の状態と目標に基づいて体験を最適化します。",
      "primaryGoal": "最も改善したい健康の目標は何ですか？",
      "weightManagement": "体重管理",
      "energyVitality": "エネルギーと活力",
      "mentalClarity": "精神の明確さ",
      "howCondition": "最近の全体的な体調はいかがですか？",
      "shareAsMuch": "お好きなだけ、ご自由に共有してください。",
      "placeholder": "例：朝起きるのが辛く、お昼過ぎには集中力が切れやすいです...",
      "startJourney": "旅を始める",
      "skipForNow": "今はスキップ",
      "configuring": "設定中...",
      "craftedFor": "© 2024 For:M. あなたのためのサンクチュアリ。"
    }
  },
  "th": {
    "nav": {
      "dashboard": "แดชบอร์ด",
      "today": "วันนี้",
      "rhythm": "จังหวะ",
      "protocols": "โปรโตคอล",
      "cycleTracking": "การติดตามรอบ",
      "community": "ชุมชน",
      "log": "บันทึก",
      "me": "โปรไฟล์",
      "welcomeBack": "ยินดีต้อนรับกลับ",
      "rhythmSteady": "จังหวะคงที่",
      "logActivity": "บันทึกกิจกรรม",
      "support": "สนับสนุน",
      "logout": "ออกจากระบบ",
      "language": "ภาษา"
    },
    "home": {
      "goodMorning": "อรุณสวัสดิ์",
      "welcomeBack": "ยินดีต้อนรับกลับ",
      "energyDay": "วันนี้เป็นวันที่มีพลังงานสูงในรอบของคุณ จงเคลื่อนไหวร่างกาย",
      "daysInRow": "วันติดต่อกัน",
      "todaysProtocol": "โปรโตคอลวันนี้",
      "weeklyRhythm": "จังหวะรายสัปดาห์",
      "synced": "ซิงค์แล้ว",
      "energyLevel": "ระดับพลังงาน",
      "optimal": "เหมาะสมที่สุด",
      "status": "สถานะ",
      "rhythmRecovery": "การฟื้นตัว",
      "lutealPhase": "ระยะลูเทียล",
      "percentOptimal": "เหมาะสม 78%",
      "quote": "\"เคลื่อนไหวเบาๆในวันนี้ ร่างกายของคุณกำลังเตรียมพร้อมสำหรับการพักผ่อน\"",
      "hormoneTracking": "ดูฮอร์โมน",
      "loggedAgo": "บันทึกเมื่อ 2 ชม. ก่อน",
      "rhythmCalendar": "ปฏิทิน",
      "nextState": "ถัดไป: โฟลว์",
      "activityRecord": "บันทึกกิจกรรม",
      "seeTrends": "ดูแนวโน้ม",
      "premiumInsight": "ข้อมูลเชิงลึกพิเศษ",
      "monthlyTrend": "รายงานแนวโน้มฮอร์โมนรายเดือน",
      "premiumText": "เราวิเคราะห์ข้อมูลชีวภาพและกิจกรรม 30 วันที่ผ่านมาของคุณ ระยะฟอลลิคูลาร์มีการปรับปรุงของอัตราการเต้นหัวใจขณะพักอย่างมีนัยสำคัญ",
      "viewReport": "ดูรายงานฉบับเต็ม",
      "needRecord": "บันทึกจังหวะ 🌿",
      "recordDesc": "ใช้เวลาเพียง 1 นาทีทุกวันเพื่อฟังร่างกายของคุณ",
      "checkinNow": "เช็คอินวันนี้",
      "howIsCycle": "รอบเดือนของคุณเป็นอย่างไรบ้าง?",
      "startCheckin": "เริ่ม",
      "currentActionRule": "ระดับกฎการกระทำสำหรับวันนี้",
      "tasks": {
        "t1_title": "เดินเช้า",
        "t1_sub": "20 นาทีกลางแจ้ง เพื่อปรับระดับคอร์ติซอล",
        "t2_title": "เป้าหมายการดื่มน้ำ",
        "t2_sub": "น้ำ 2.5 ลิตรพร้อมอิเล็กโทรไลต์",
        "t3_title": "คุณภาพการนอนหลับ",
        "t3_sub": "ติดตามรอบการหลับลึกและ REM"
      }
    },
    "onboarding": {
      "findingRhythm": "ค้นหาจังหวะของคุณ",
      "tailorExperience": "เราจะปรับประสบการณ์ของคุณตามสถานะและแรงบันดาลใจปัจจุบัน",
      "primaryGoal": "เป้าหมายสุขภาพคืออะไร?",
      "weightManagement": "การจัดการน้ำหนัก",
      "energyVitality": "พลังงานและความมีชีวิตชีวา",
      "mentalClarity": "ความชัดเจนทางจิตใจ",
      "howCondition": "สภาพร่างกายทั่วไปของคุณเป็นอย่างไร?",
      "shareAsMuch": "คุณสามารถแชร์มากน้อยตามที่คุณต้องการ",
      "placeholder": "ตัวอย่าง: รู้สึกอ่อนล้าในตอนเช้าและไม่มีสมาธิในตอนบ่าย...",
      "startJourney": "เริ่มต้น",
      "skipForNow": "ข้าม",
      "configuring": "กำลังตั้งค่า...",
      "craftedFor": "© 2024 For:M สร้างขึ้นเพื่อคุณ"
    }
  },
  "vi": {
    "nav": {
      "dashboard": "Bảng điều khiển",
      "today": "HÔM NAY",
      "rhythm": "NHỊP ĐỘ",
      "protocols": "Quy trình",
      "cycleTracking": "Theo dõi chu kỳ",
      "community": "Cộng đồng",
      "log": "NHẬT KÝ",
      "me": "TÔI",
      "welcomeBack": "Chào mừng trở lại",
      "rhythmSteady": "Nhịp độ của bạn rất ổn định",
      "logActivity": "Ghi chép hoạt động",
      "support": "Hỗ trợ",
      "logout": "Đăng xuất",
      "language": "Ngôn ngữ"
    },
    "home": {
      "goodMorning": "Chào buổi sáng",
      "welcomeBack": "Chào mừng trở lại",
      "energyDay": "Hôm nay là một ngày nhiều năng lượng. Hãy hoạt động tích cực.",
      "daysInRow": "NGÀY LIÊN TIẾP",
      "todaysProtocol": "Quy trình hôm nay",
      "weeklyRhythm": "Nhịp độ hàng tuần",
      "synced": "ĐỒNG BỘ",
      "energyLevel": "Mức năng lượng",
      "optimal": "Tối ưu",
      "status": "TRẠNG THÁI",
      "rhythmRecovery": "Đang phục hồi",
      "lutealPhase": "Giai đoạn hoàng thể",
      "percentOptimal": "78% Tối ưu",
      "quote": "\"Hãy chuyển động nhẹ nhàng; cơ thể bạn đang chuẩn bị nghỉ ngơi.\"",
      "hormoneTracking": "Theo dõi hormone",
      "loggedAgo": "Đã ghi 2h trước",
      "rhythmCalendar": "Lịch nhịp độ",
      "nextState": "Tiếp theo: Flow State",
      "activityRecord": "Kỷ lục hoạt động",
      "seeTrends": "Xem xu hướng",
      "premiumInsight": "Thông tin độc quyền",
      "monthlyTrend": "Báo cáo xu hướng hormone",
      "premiumText": "Chúng tôi đã phân tích trong 30 ngày qua. Nhịp tim khi nghỉ ngơi của bạn ở giai đoạn nang trứng đã được cải thiện.",
      "viewReport": "XEM BÁO CÁO ĐẦY ĐỦ",
      "needRecord": "Cần Ghi chép 🌿",
      "recordDesc": "Hãy dành 1 phút để lắng nghe cơ thể bạn.",
      "checkinNow": "Bắt đầu Check-in",
      "howIsCycle": "Chu kỳ của bạn thế nào?",
      "startCheckin": "Bắt đầu",
      "currentActionRule": "Hướng dẫn hành động cho bạn",
      "tasks": {
        "t1_title": "Đi bộ buổi sáng",
        "t1_sub": "20 phút ngoài trời để điều chỉnh cortisol",
        "t2_title": "Mục tiêu nước",
        "t2_sub": "2.5L với điện giải",
        "t3_title": "Ngủ chất lượng",
        "t3_sub": "Theo dõi chu kỳ giấc ngủ REM"
      }
    },
    "onboarding": {
      "findingRhythm": "Tìm nhịp độ",
      "tailorExperience": "Tùy chỉnh trải nghiệm của bạn.",
      "primaryGoal": "Mục tiêu sức khỏe?",
      "weightManagement": "Quản lý cân nặng",
      "energyVitality": "Năng lượng",
      "mentalClarity": "Sự minh mẫn",
      "howCondition": "Gần đây bạn cảm thấy thế nào?",
      "shareAsMuch": "Chia sẻ những gì bạn muốn.",
      "placeholder": "Ví dụ: Hay mệt mỏi vào buổi sáng và khó tập trung...",
      "startJourney": "Bắt đầu",
      "skipForNow": "Bỏ qua",
      "configuring": "Đang cài đặt...",
      "craftedFor": "© 2024 For:M Dành riêng cho bạn"
    }
  },
  "de": {
    "nav": {
      "dashboard": "Dashboard",
      "today": "HEUTE",
      "rhythm": "RHYTHMUS",
      "protocols": "Protokolle",
      "cycleTracking": "Zyklus",
      "community": "Community",
      "log": "LOGbuch",
      "me": "ICH",
      "welcomeBack": "Willkommen zurück",
      "rhythmSteady": "Dein Rhythmus ist stabil",
      "logActivity": "Aktivität erfassen",
      "support": "Hilfe",
      "logout": "Abmelden",
      "language": "Sprache"
    },
    "home": {
      "goodMorning": "Guten Morgen",
      "welcomeBack": "Willkommen zurück",
      "energyDay": "Heute ist ein energiereicher Tag in deinem Zyklus. Nutze die Kraft.",
      "daysInRow": "TAGE IN FOLGE",
      "todaysProtocol": "Heutiges Protokoll",
      "weeklyRhythm": "Wochenrhythmus",
      "synced": "SYNCHRON",
      "energyLevel": "Energielevel",
      "optimal": "Optimal",
      "status": "STATUS",
      "rhythmRecovery": "Rhythmus-Erholung",
      "lutealPhase": "Lutealphase",
      "percentOptimal": "78% Optimal",
      "quote": "\"Bewege dich heute sanft; dein Körper bereitet sich auf Ruhe vor.\"",
      "hormoneTracking": "Hormon-Tracking",
      "loggedAgo": "Vor 2h erfasst",
      "rhythmCalendar": "Rhythmus-Kalender",
      "nextState": "Nächster: Flow",
      "activityRecord": "Aktivitätsverlauf",
      "seeTrends": "Trends ansehen",
      "premiumInsight": "Premium Insight",
      "monthlyTrend": "Monatlicher Hormon-Trend",
      "premiumText": "Wir haben deine Gesundheitsdaten der letzten 30 Tage analysiert. Deine Follikelphase zeigt Verbesserungen der Herzfrequenzvariabilität.",
      "viewReport": "BERICHT ANSEHEN",
      "needRecord": "Eintrag fehlt 🌿",
      "recordDesc": "Nimm dir 1 Minute, um auf die Zeichen deines Körpers zu hören.",
      "checkinNow": "Check-in starten",
      "howIsCycle": "Wie geht es deinem Zyklus?",
      "startCheckin": "Starten",
      "currentActionRule": "Aktuelle Handlungsempfehlungen",
      "tasks": {
        "t1_title": "Morgenspaziergang",
        "t1_sub": "20 Minuten im Freien für Cortisol",
        "t2_title": "Trinkziel",
        "t2_sub": "2.5L Wasser mit Elektrolyten",
        "t3_title": "Schlafqualität",
        "t3_sub": "REM- und Tiefschlaf-Tracking"
      }
    },
    "onboarding": {
      "findingRhythm": "Finde deinen Rhythmus",
      "tailorExperience": "Wir passen die App an deine Ziele an.",
      "primaryGoal": "Was ist dein Hauptziel?",
      "weightManagement": "Gewichtsmanagement",
      "energyVitality": "Energie & Vitalität",
      "mentalClarity": "Mentale Klarheit",
      "howCondition": "Wie fühlst du dich generell in letzter Zeit?",
      "shareAsMuch": "Teile so viel, wie du möchtest.",
      "placeholder": "Beispiel: Ich fühle mich morgens schlapp und kann mich nachmittags schlecht konzentrieren...",
      "startJourney": "Reise beginnen",
      "skipForNow": "Jetzt überspringen",
      "configuring": "Wird konfiguriert...",
      "craftedFor": "© 2024 For:M. Gemacht für dein Wohlbefinden."
    }
  },
  "fr": {
    "nav": {
      "dashboard": "Tableau de Bord",
      "today": "AUJ",
      "rhythm": "RYTHME",
      "protocols": "Protocoles",
      "cycleTracking": "Cycle",
      "community": "Communauté",
      "log": "JOURNAL",
      "me": "MOI",
      "welcomeBack": "Bon retour",
      "rhythmSteady": "Votre rythme est stable",
      "logActivity": "Ajouter activité",
      "support": "Support",
      "logout": "Déconnexion",
      "language": "Langue"
    },
    "home": {
      "goodMorning": "Bonjour",
      "welcomeBack": "Bon retour",
      "energyDay": "Aujourd'hui, énergie maximale dans votre cycle. Profitez-en.",
      "daysInRow": "JOURS CONSÉCUTIFS",
      "todaysProtocol": "Protocole du jour",
      "weeklyRhythm": "Rythme de la semaine",
      "synced": "SYNCHRO",
      "energyLevel": "Niveau d'énergie",
      "optimal": "Optimal",
      "status": "STATUT",
      "rhythmRecovery": "Récupération",
      "lutealPhase": "Phase Lutéale",
      "percentOptimal": "78% Optimal",
      "quote": "\"Mouvements doux aujourd'hui; votre corps se prépare au repos.\"",
      "hormoneTracking": "Hormones",
      "loggedAgo": "Ajouté il y a 2h",
      "rhythmCalendar": "Calendrier Rythme",
      "nextState": "Suivant: Flow",
      "activityRecord": "Activités Récentes",
      "seeTrends": "Voir Tendances",
      "premiumInsight": "Aperçu Premium",
      "monthlyTrend": "Rapport Mensuel Hormones",
      "premiumText": "Analyse des 30 derniers jours. Votre phase folliculaire montre une belle amélioration de la variabilité cardiaque.",
      "viewReport": "VOIR LE RAPPORT COMPLET",
      "needRecord": "Enregistrement Requis 🌿",
      "recordDesc": "Prenez 1 minute pour écouter votre corps.",
      "checkinNow": "Commencer Check-in",
      "howIsCycle": "Comment va votre cycle ?",
      "startCheckin": "Démarrer",
      "currentActionRule": "Directives personnalisées",
      "tasks": {
        "t1_title": "Marche Matinale",
        "t1_sub": "20 min en extérieur (Cortisol)",
        "t2_title": "Objectif Hydratation",
        "t2_sub": "2.5L avec électrolytes",
        "t3_title": "Qualité de Sommeil",
        "t3_sub": "Suivi des cycles REM/Profonds"
      }
    },
    "onboarding": {
      "findingRhythm": "Trouvez votre rythme",
      "tailorExperience": "Expérience sur-mesure basée sur vos objectifs.",
      "primaryGoal": "Principal objectif de santé ?",
      "weightManagement": "Gestion du Poids",
      "energyVitality": "Énergie & Vitalité",
      "mentalClarity": "Clarté Mentale",
      "howCondition": "Comment vous sentez-vous récemment ?",
      "shareAsMuch": "Partagez ce que vous souhaitez.",
      "placeholder": "Ex: Je me sens fatiguée le matin et du mal à me concentrer l'après-midi...",
      "startJourney": "Commencer",
      "skipForNow": "Passer pour l'instant",
      "configuring": "Configuration...",
      "craftedFor": "© 2024 For:M. Créé pour votre bien-être."
    }
  },
  "zh-CN": {
    "nav": {
      "dashboard": "首页",
      "today": "今天",
      "rhythm": "节律",
      "protocols": "方案",
      "cycleTracking": "周期追踪",
      "community": "社区",
      "log": "记录",
      "me": "我的",
      "welcomeBack": "欢迎回来",
      "rhythmSteady": "您的节律非常稳定",
      "logActivity": "记录状态",
      "support": "支持",
      "logout": "退出登录",
      "language": "语言"
    },
    "home": {
      "goodMorning": "早上好",
      "welcomeBack": "欢迎回来",
      "energyDay": "今天您的能量水平很高，去释放活力吧。",
      "daysInRow": "连续打卡",
      "todaysProtocol": "今日方案",
      "weeklyRhythm": "周节律",
      "synced": "已同步",
      "energyLevel": "能量水平",
      "optimal": "最佳",
      "status": "状态",
      "rhythmRecovery": "节律恢复中",
      "lutealPhase": "黄体期",
      "percentOptimal": "78% 最佳",
      "quote": "“今天请选择温和的运动，身体正在为休息做准备。”",
      "hormoneTracking": "激素追踪",
      "loggedAgo": "2小时前记录",
      "rhythmCalendar": "节律日历",
      "nextState": "下一个: 心流状态",
      "activityRecord": "活动记录",
      "seeTrends": "查看趋势",
      "premiumInsight": "深度洞察",
      "monthlyTrend": "月度内分泌趋势报告",
      "premiumText": "基于过去30天的数据分析。您的卵泡期静息心率变异性有明显改善。",
      "viewReport": "查看完整报告",
      "needRecord": "需要记录 🌿",
      "recordDesc": "每天只需1分钟，倾听身体细微的变化。",
      "checkinNow": "今日状态打卡",
      "howIsCycle": "您的周期状态如何？",
      "startCheckin": "开始打卡",
      "currentActionRule": "适合当下的行动指南",
      "tasks": {
        "t1_title": "晨间散步",
        "t1_sub": "户外20分钟调节皮质醇",
        "t2_title": "补水目标",
        "t2_sub": "2.5L水，含电解质",
        "t3_title": "睡眠质量记录",
        "t3_sub": "追踪REM和深度睡眠"
      }
    },
    "onboarding": {
      "findingRhythm": "寻找您的专属节律",
      "tailorExperience": "我们将为您量身定制个人体验。",
      "primaryGoal": "您最想改善的健康目标是什么？",
      "weightManagement": "体重管理",
      "energyVitality": "能量与活力",
      "mentalClarity": "保持头脑清晰",
      "howCondition": "最近的整体状态如何？",
      "shareAsMuch": "您可以随便聊聊。",
      "placeholder": "例如：早上总是很难起床，下午容易犯困走神...",
      "startJourney": "开启旅程",
      "skipForNow": "跳过",
      "configuring": "正在设置...",
      "craftedFor": "© 2024 For:M 为您的身心打造。"
    }
  },
  "zh-TW": {
    "nav": {
      "dashboard": "主頁",
      "today": "今天",
      "rhythm": "節律",
      "protocols": "方案",
      "cycleTracking": "週期追蹤",
      "community": "社群",
      "log": "紀錄",
      "me": "我的",
      "welcomeBack": "歡迎回來",
      "rhythmSteady": "您的節律非常穩定",
      "logActivity": "紀錄狀態",
      "support": "支援",
      "logout": "登出",
      "language": "語言"
    },
    "home": {
      "goodMorning": "早安",
      "welcomeBack": "歡迎回來",
      "energyDay": "今天您的能量滿滿，去釋放活力吧。",
      "daysInRow": "連續打卡",
      "todaysProtocol": "今日方案",
      "weeklyRhythm": "週節律",
      "synced": "已同步",
      "energyLevel": "能量水準",
      "optimal": "最佳",
      "status": "狀態",
      "rhythmRecovery": "節律恢復中",
      "lutealPhase": "黃體期",
      "percentOptimal": "78% 最佳",
      "quote": "「今天請選擇溫和的運動，身體正在為休息做準備。」",
      "hormoneTracking": "荷爾蒙追蹤",
      "loggedAgo": "2小時前紀錄",
      "rhythmCalendar": "節律日曆",
      "nextState": "下一個: 心流狀態",
      "activityRecord": "活動記錄",
      "seeTrends": "查看趨勢",
      "premiumInsight": "深度洞察",
      "monthlyTrend": "月度內分泌趨勢報告",
      "premiumText": "基於過去30天的數據分析。您的卵泡期靜息心率變異性有明顯改善。",
      "viewReport": "查看完整報告",
      "needRecord": "需要紀錄 🌿",
      "recordDesc": "每天只需1分鐘，傾聽身體細微的變化。",
      "checkinNow": "今日狀態打卡",
      "howIsCycle": "您的週期狀態如何？",
      "startCheckin": "開始打卡",
      "currentActionRule": "適合當下的行動指南",
      "tasks": {
        "t1_title": "晨間散步",
        "t1_sub": "戶外20分鐘調節皮質醇",
        "t2_title": "補水目標",
        "t2_sub": "2.5L水，含電解質",
        "t3_title": "睡眠品質紀錄",
        "t3_sub": "追蹤REM和深度睡眠"
      }
    },
    "onboarding": {
      "findingRhythm": "尋找您的專屬節律",
      "tailorExperience": "我們將為您量身打造個人體驗。",
      "primaryGoal": "您最想改善的健康目標是什麼？",
      "weightManagement": "體重管理",
      "energyVitality": "能量與活力",
      "mentalClarity": "保持頭腦清晰",
      "howCondition": "最近的整體狀態如何？",
      "shareAsMuch": "您可以隨便聊聊。",
      "placeholder": "例如：早上總是起不來，下午容易犯睏分心...",
      "startJourney": "開啟旅程",
      "skipForNow": "跳過",
      "configuring": "正在設定...",
      "craftedFor": "© 2024 For:M 為您的身心打造。"
    }
  }
};

const dicPath = path.join(__dirname, 'src', 'dictionaries');
if (!fs.existsSync(dicPath)) fs.mkdirSync(dicPath, { recursive: true });

Object.entries(dictionaries).forEach(([lang, data]) => {
  fs.writeFileSync(path.join(dicPath, `${lang}.json`), JSON.stringify(data, null, 2));
});
console.log('Dictionaries generated.');
